### ISSUE TITLE
Spotify Notifications is damaged

### ISSUE THREAD

**Issue by ttmjason** [citruspi/Spotify-Notifications#42] opened 2015-02-26 19:22 UTC
I'm getting this error message, even after I delete it and try downloading a new version:

"“Spotify Notifications.app” is damaged and can’t be opened. You should move it to the Trash."

I'm on OSX Yosemite 10.10.1, late 2012 Mac Mini.

**Comment by citruspi** [comment] 2015-02-26 19:57
@ttmjason,

This is a duplicate of #40.

&mdash; @citruspi

**Closed by citruspi** 2015-02-26 19:57 UTC
