### ISSUE TITLE
File damaged

### ISSUE THREAD

**Issue by luisfrocha** [citruspi/Spotify-Notifications#43] opened 2015-03-06 22:57 UTC
When I try to open the app, OS X tells me the file is damaged and it should be moved to the trash can. I've scanned it for viruses and it's clean. I've already downloaded a few times and still get the same message. Not sure what else to try.

![screen shot 2015-03-06 at 4 55 43 pm](https://cloud.githubusercontent.com/assets/7130389/6537967/b4dbf0bc-c421-11e4-981a-0133d287da02.png)

**Comment by citruspi** [comment] 2015-03-09 13:58
@luisfrocha,

This is a duplicate of #40.

&mdash; @citruspi

**Closed by citruspi** 2015-03-09 13:58 UTC
