### ISSUE TITLE
Notification banners not functioning

### ISSUE THREAD

**Issue by dillonkrug** [citruspi/Spotify-Notifications#38] opened 2014-12-31 17:27 UTC
I just installed this app and it's not working for me (I'm using Yosemite)

I set a global shortcut and I can hear the sound when I use it, but no banner shows up.  The notification shows up in notification center, but I'm not sure that's working properly either - it only shows "Spotifiy Notifications"

![screen shot 2014-12-31 at 12 24 31 pm](https://cloud.githubusercontent.com/assets/3105014/5589227/1304562e-90e8-11e4-9c6d-9cd1349e118e.png)

Also, there aren't any notifications that I didn't trigger using the current song shortcut.

I have checked the settings in system preferences, and everything appears to be in order.

**Comment by citruspi** [comment] 2015-01-07 23:56
Hey @dillonkrug,

Thanks for letting me know about this issue.

To be honest, OS X development isn't my forte and I'm not sure how to go about debugging this issue. I'd like to rewrite the project in the near future - the code isn't as clean as it could be. I'll let you know when I've gotten around to a rewrite.

In the meantime, let me know if anything changes.

Thanks.

&mdash; @citruspi

**Comment by magonzz** [comment] 2015-03-11 09:26
I'm having a similar issue where using the keyboard shortcut set by me isn't bringing up a banner with details on the currently playing song. It only notifies me with a banner at the start of a new track, but that's it. The notifications in the Notification Center are working properly for me.

**Comment by smctradeshift** [comment] 2015-03-23 18:27
I am seeing the same problem. The banner will appear when a new track starts or when I press pause/play.

**Comment by vogler** [comment] 2015-07-24 09:22
The shortcut only works reliably for me if the preferences dialog has focus. Strangely, sometimes, it also works when it's closed - I couldn't reproduce it though.

**Comment by studgeek** [comment] 2015-08-08 20:27
Can you rename this issue to better show its for keyboard shortcuts?

**Comment by albenesi** [comment] 2015-08-17 16:16
Just want to confirm that I also have this issue. It's the same as issue #45.

**Comment by gerbenjacobs** [comment] 2015-09-09 09:29
"Show Current Song" shortcut only works when Plugin is focused. This is on Yosemite 10.10.5 and I didn't notice it before I upgraded.

The normal popups do work.

**Comment by numblock** [comment] 2016-02-17 09:55
+1

**Comment by J0HAN85** [comment] 2016-07-25 20:51
Check this: https://github.com/citruspi/Spotify-Notifications/issues/62
Keyboard shortcut works when you set "Show only current song" to disabled.

**Comment by nwself** [comment] 2016-07-26 19:11
This workaround from @J0HAN85 makes my keyboard shortcut work again too.

**Comment by citruspi** [comment] 2016-09-30 15:31
This issue has been fixed in #56.

**Closed by citruspi** 2016-09-30 15:31 UTC
Labels: bug
