### ISSUE TITLE
Should be able to close notification

### ISSUE THREAD

**Issue by facundofarias** [citruspi/Spotify-Notifications#41] opened 2015-02-26 10:16 UTC
Once the notification is shown, the user should be able to close it (with an X button, or something like that). Otherwise, if you need to use that part of the screen, for a few seconds it's "locked".

**Comment by citruspi** [comment] 2015-02-26 15:46
@facundofarias,

I'm closing this as it's a duplicate of  #34.

&mdash; @citruspi

**Closed by citruspi** 2015-02-26 15:46 UTC

**Comment by facundofarias** [comment] 2015-02-26 15:50
Yeah, sorry I did a quick search and I didn't find it (or I was too sleepy).
Thanks
